from collections import defaultdict

from agents.extraction_agent import ListingData
from agents.vin_agent import VINData
from agents.photo_agent import PhotoAnalysis
from core.verifier import verify_listing, Flag
from core.constants import CONFIDENCE_FLOOR
from eval.eval_runner import ERROR_FIELD_ALIASES, SEVERITY_ORDER, SYNTHETIC_NOISE_FIELDS, _STUB_EDITORIAL
from analysis.common import load_results, load_matched_round1, write_json

CHANGED_FIELDS = {"mileage", "engine_displacement", "engine_cylinders", "duplicate_photos", "color", "photo_angles"}
_PHOTO_FIELDS = set(PhotoAnalysis.model_fields.keys())


def _build_photo(p: dict) -> PhotoAnalysis:
    return PhotoAnalysis(**{k: v for k, v in p.items() if k in _PHOTO_FIELDS})


def _recompute_row(entry: dict) -> tuple[list[Flag], list[dict]]:
    """Reruns the CURRENT (new-code) verify_listing() against a round1
    entry's already-stored inputs. Returns (post-floor flags, pre-floor
    flag dicts) -- pre-floor is what calibration-style analysis needs."""
    listing = ListingData(**entry["listing_data"])
    vin = VINData(**entry["vin_data"])
    photos = [_build_photo(p) for p in (entry.get("photos") or [])]
    dup_pairs = [
        (p["url_a"], p["url_b"], p["hamming_distance"])
        for p in (entry.get("duplicate_photo_pairs") or [])
    ]
    flags, summary = verify_listing(listing, vin, photos, _STUB_EDITORIAL, dup_pairs)
    before_floor = [
        {"field_name": f.flag.field_name, "confidence": f.flag.confidence, "severity": f.flag.severity}
        for f in summary.all_flags_before_floor
    ]
    return flags, before_floor


def _bin_stats(observations: list[dict], bin_width: float = 0.05) -> list[dict]:
    """Numeric bins, not exact-value grouping -- appropriate now that
    these 6 checks produce continuously-varying confidence, unlike
    calibration.py's exact-value grouping which fits the *unchanged*
    checks (year, make, drivetrain, transmission) that still use fixed
    constants."""
    # Track (confidence, label) together per bin, not just labels -- an
    # earlier version re-filtered `observations` a second time by
    # confidence to compute the mean, using a `bin_low <= x < bin_low +
    # bin_width` boundary check. That silently produced 0.0 whenever a
    # value (e.g. exactly 0.9) landed precisely on a bin edge, because
    # `//` on floats doesn't always floor to the bin you'd expect (0.9 //
    # 0.05 rounds to 17 instead of 18 due to float imprecision) while the
    # boundary re-check used strict "<", excluding the value from its own
    # bin. Keeping both values together from the start avoids ever needing
    # that fragile second comparison.
    bins = defaultdict(list)
    for obs in observations:
        bin_key = round(obs["confidence"] // bin_width * bin_width, 2)
        bins[bin_key].append((obs["confidence"], obs["label"]))
    out = []
    for bin_low in sorted(bins):
        pairs = bins[bin_low]
        n = len(pairs)
        observed = sum(label for _, label in pairs) / n
        mean_confidence = sum(conf for conf, _ in pairs) / n
        out.append({
            "bin_low": bin_low,
            "bin_high": round(bin_low + bin_width, 2),
            "n": n,
            "observed_correct_rate": round(observed, 4),
            "mean_confidence_in_bin": round(mean_confidence, 4),
        })
    return out


def run() -> dict:
    results = load_results()
    matched_round1 = load_matched_round1(results)

    old_field_obs = defaultdict(list)  # from stored (old-code) round1_results.json
    new_field_obs = defaultdict(list)  # from freshly recomputed (new-code) flags

    tp_delta_rows = []  # rows where catching the injected error changed old->new
    n_processed = 0

    for auction_id, entry in matched_round1.items():
        error_field = entry["error_field"]
        expected_severity = entry["expected_flag_severity"]
        aliases = ERROR_FIELD_ALIASES.get(error_field, [error_field])

        vs = entry.get("verification_summary")
        if not vs or "all_flags_before_floor" not in vs:
            continue
        n_processed += 1

        # --- OLD: as already stored (generated by the pre-change code) ---
        for item in vs["all_flags_before_floor"]:
            f = item["flag"]
            if f["field_name"] not in CHANGED_FIELDS:
                continue
            matches = f["field_name"] in aliases
            if not matches and f["field_name"] in SYNTHETIC_NOISE_FIELDS:
                continue
            old_field_obs[f["field_name"]].append({"confidence": f["confidence"], "label": 1 if matches else 0})

        # --- NEW: recomputed fresh with the current (changed) code ---
        new_flags, new_before_floor = _recompute_row(entry)
        for f in new_before_floor:
            if f["field_name"] not in CHANGED_FIELDS:
                continue
            matches = f["field_name"] in aliases
            if not matches and f["field_name"] in SYNTHETIC_NOISE_FIELDS:
                continue
            new_field_obs[f["field_name"]].append({"confidence": f["confidence"], "label": 1 if matches else 0})

        # --- Recall side-effect check: did catching the planted error
        # change between old (stored) and new (recomputed) at the real
        # CONFIDENCE_FLOOR? ---
        old_caught = any(
            f["field_name"] in aliases
            and f["confidence"] >= CONFIDENCE_FLOOR
            and SEVERITY_ORDER.get(f["severity"], 99) <= SEVERITY_ORDER.get(expected_severity, 99)
            for f in [item["flag"] for item in vs["all_flags_before_floor"]]
        )
        new_caught = any(
            f.field_name in aliases
            and f.confidence >= CONFIDENCE_FLOOR
            and SEVERITY_ORDER.get(f.severity, 99) <= SEVERITY_ORDER.get(expected_severity, 99)
            for f in new_flags
        )
        if old_caught != new_caught and error_field in aliases:
            tp_delta_rows.append({
                "auction_id": auction_id,
                "error_type": entry["error_type"],
                "error_field": error_field,
                "old_caught": old_caught,
                "new_caught": new_caught,
                "direction": "NEWLY MISSED (regression)" if old_caught and not new_caught else "NEWLY CAUGHT (improvement)",
            })

    comparison = {}
    for field in sorted(CHANGED_FIELDS):
        old_obs = old_field_obs.get(field, [])
        new_obs = new_field_obs.get(field, [])
        old_brier = round(sum((o["confidence"] - o["label"]) ** 2 for o in old_obs) / len(old_obs), 4) if old_obs else None
        new_brier = round(sum((o["confidence"] - o["label"]) ** 2 for o in new_obs) / len(new_obs), 4) if new_obs else None
        comparison[field] = {
            "old_brier_score": old_brier,
            "new_brier_score": new_brier,
            "brier_improved": (
                "improved" if new_brier < old_brier
                else "unchanged" if new_brier == old_brier
                else "worse"
            ) if (old_brier is not None and new_brier is not None) else None,
            "old_n": len(old_obs),
            "new_n": len(new_obs),
            "old_bins_exact_value": _exact_value_bins(old_obs),
            "new_bins_numeric": _bin_stats(new_obs),
        }

    regressions = [r for r in tp_delta_rows if r["direction"].startswith("NEWLY MISSED")]
    improvements = [r for r in tp_delta_rows if r["direction"].startswith("NEWLY CAUGHT")]

    output = {
        "analysis": "confidence_scaling_validation",
        "purpose": (
            "Before/after check for the smooth-confidence change to core/verifier.py's "
            "mileage/engine_displacement/engine_cylinders/duplicate_photos/color/photo_angles "
            "checks -- did calibration actually improve, and did the new formulas' lower "
            "floors accidentally push any real catch below CONFIDENCE_FLOOR=0.70?"
        ),
        "n_rows_processed": n_processed,
        "per_field_comparison": comparison,
        "recall_side_effect_check": {
            "n_rows_with_changed_catch_status": len(tp_delta_rows),
            "regressions_newly_missed": regressions,
            "improvements_newly_caught": improvements,
        },
    }
    return output


def _exact_value_bins(observations: list[dict]) -> list[dict]:
    by_conf = defaultdict(list)
    for obs in observations:
        by_conf[obs["confidence"]].append(obs["label"])
    return [
        {"confidence": conf, "n": len(labels), "observed_correct_rate": round(sum(labels) / len(labels), 4)}
        for conf, labels in sorted(by_conf.items())
    ]


if __name__ == "__main__":
    output = run()
    path = write_json(output, "confidence_scaling_validation.json")
    print(f"Confidence scaling validation written to {path}")
    print(f"\n{output['n_rows_processed']} rows processed (recomputed with zero new API cost)")

    print("\n=== Brier score: before (fixed constant) vs after (scaled) ===")
    for field, c in output["per_field_comparison"].items():
        arrow = (c["brier_improved"] or "N/A").upper()
        print(f"  {field:20s} old={c['old_brier_score']}  new={c['new_brier_score']}  [{arrow}]")

    side = output["recall_side_effect_check"]
    print(f"\n=== Recall side-effect check ===")
    print(f"Rows where catch status changed: {side['n_rows_with_changed_catch_status']}")
    print(f"  Regressions (newly missed, a real catch pushed below the floor): {len(side['regressions_newly_missed'])}")
    for r in side["regressions_newly_missed"]:
        print(f"    {r}")
    print(f"  Improvements (newly caught): {len(side['improvements_newly_caught'])}")
    for r in side["improvements_newly_caught"]:
        print(f"    {r}")
